# Generated by Django 4.2.1 on 2023-05-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('date_out', models.DateTimeField()),
                ('synopsis', models.TextField()),
                ('genre', models.CharField(max_length=100)),
                ('format_type', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('thumb', models.ImageField(blank=True, default='logo.JPG', upload_to='')),
            ],
        ),
    ]
