# Generated by Django 4.2.1 on 2023-05-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='date_out',
            field=models.CharField(max_length=100),
        ),
    ]
