# Generated by Django 5.2.17 on 2026-09-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_alter_film_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='release_date',
            field=models.DateField(blank=True, help_text='Date exacte de sortie (pour le tri chronologique)', null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='status',
            field=models.CharField(choices=[('now_showing', 'Actuellement en salle'), ('upcoming', 'Prochainement')], default='now_showing', help_text='En salle ou sortie future', max_length=20),
        ),
        migrations.AlterField(
            model_name='film',
            name='date_out',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='film',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
