# Generated by Django 5.2.17 on 2026-09-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_film_release_date_film_status_alter_film_date_out_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Programme de la Semaine', help_text='ex: Programme de la Semaine du 11 au 17 Septembre 2026', max_length=200)),
                ('start_date', models.DateField(blank=True, help_text='Date de début (ex: 2026-09-11)', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Date de fin (ex: 2026-09-17)', null=True)),
                ('poster', models.ImageField(blank=True, help_text='Affiche officielle du programme', null=True, upload_to='schedules/')),
                ('subtitle', models.CharField(default="Consultez l'affiche officielle des séances, horaires et tarifs de la semaine en cours.", max_length=300)),
                ('notice', models.CharField(blank=True, default='🎬 Navette gratuite Ahala ↔ Mbankomo pour toutes les séances à partir de 18h00 !', max_length=300)),
                ('price_standard', models.CharField(default='3 000 XAF', max_length=50)),
                ('price_under_12', models.CharField(default='1 500 XAF', max_length=50)),
                ('price_glasses_3d', models.CharField(default='1 500 XAF', max_length=50)),
                ('price_premiere', models.CharField(default='5 000 XAF', max_length=50)),
                ('price_avant_premiere', models.CharField(default='5 000 XAF', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Afficher ce programme sur le site public')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
